name: docker-hub-push

on: 
  push:
    branches:
       - 'main'
       - 'feature/*'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Image
        run: |
          docker build -t rushikeshghodkedottech/node-app:${{ github.sha }} .

      - name: Push to Docker Hub
        run: |
          docker push rushikeshghodkedottech/node-app:${{ github.sha }}
        if: github.ref == 'refs/heads/main'
        


        
